spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-1
            uri: http://localhost:8081/
            predicates:
              - Path=/service1/**
            filters:
              - StripPrefix=1
          - id: ms-2
            uri: http://localhost:8082/
            predicates:
              - Path=/service2/**
            filters:
              - StripPrefix=1